DROP TABLE IF EXISTS USER_PRODUCT;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS PRODUCT (
	product_id INT	UNSIGNED AUTO_INCREMENT NOT NULL
	,title VARCHAR(100) NOT NULL
	,total_investing_amount int NOT NULL DEFAULT 0
	,current_recruitment_amount int NOT NULL DEFAULT 0
	,investors_cnt int NOT NULL DEFAULT 0
	,started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	,finished_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

	,PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS USERS (
	user_id INT	UNSIGNED AUTO_INCREMENT NOT NULL
	,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
	,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

	,PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS USER_PRODUCT (
   seq INT UNSIGNED AUTO_INCREMENT NOT NULL
	,product_id	INT UNSIGNED	NOT NULL
	,user_id	INT UNSIGNED	NOT NULL
	,my_investing_amount	INT NOT NULL
	,investing_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

	,PRIMARY KEY (seq)
    ,CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES product(product_id) on update cascade on delete cascade
	,CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(user_id) on update cascade on delete cascade
);